# Generated by Django 4.2.2 on 2023-06-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=32, verbose_name='Firstname')),
                ('lastname', models.CharField(max_length=32, verbose_name='Lastname')),
                ('about', models.TextField(verbose_name='About')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
