# Generated by Django 4.2.2 on 2023-06-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_cv_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cv',
            options={'verbose_name': 'Student'},
        ),
        migrations.AddField(
            model_name='cv',
            name='image',
            field=models.ImageField(default='https://thumbs.dreamstime.com/b/no-user-profile-picture-hand-drawn-illustration-53840792.jpg', upload_to='cv_images/', verbose_name='Image'),
        ),
    ]
