# Generated by Django 4.2.2 on 2023-06-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_alter_cv_options_cv_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='short',
            field=models.CharField(default=(), max_length=64, verbose_name='Shortdesc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cv',
            name='image',
            field=models.ImageField(default='media/default.jpg', upload_to='media', verbose_name='Image'),
        ),
    ]
