# Generated by Django 4.2.2 on 2023-06-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0004_cv_short_alter_cv_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='media/default.jpg', upload_to='media', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Galery',
            },
        ),
    ]
